project:
  type: "website"
  output-dir: /home/jasmine/MLDS/mlds_R/docs

website: 
  favicon: mlds_logo.png

  page-footer: 
    left: "Built with [Quarto](https://quarto.org/) and [Quarto Live](https://r-wasm.github.io/quarto-live/)"
    background: "#B0C4DE"

  navbar:
    background: "#B0C4DE"
    search: true
    left:
      - text: "Interactive demo"
        href: index.qmd
      - text: "Static demo"
        href: static.qmd
    right: 
      - icon: github
        href: https://github.com/jasminex21/mlds_R

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    css: styles.css 

editor:
  render-on-save: true



