project:
  type: "website"
  output-dir: /home/jasmine/MLDS/mlds_R/docs

website: 
  favicon: mlds_logo.png

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true

editor:
  render-on-save: true



